[package]
name = "gl"
version = "0.1.0"
authors = ["Juuso Tuononen <jutuon@outlook.com>"]
publish = false

[features]
gles = []

[dependencies]
cgmath = "0.15.0"

[build-dependencies]
gl_generator = "0.7.0"